### ISSUE TITLE
Protocole (Rajout)

### ISSUE THREAD

**Issue by Rekkuzan** [RTYPE-EPITECH/RType#5]
Il faudrait rajouté : 
(new)- Un packet pour notifier au client où on en est dans le scroll. (Le jeu scroll horizontalement, le server doit envoyer à chaque boucle de combien de pixel ça a scrollé) (DONE)
(new)- Un packet pour "initialisé" les entités pour le client : Nom de l'entité, chemin de l'image, taille (DONE)
(new) - Packet pour dire quand un joueur arrive dans la partie (EN COURS...)
(new) - Packet pour dire qu'une entité est morte (Joueur, Monstre, Missile, obstacle)
(modif) - Packet Error : Des messages en plus (Fail to shoot, Fail to move) (DONE)
(modif)- Le packet pour indiquer la position d'un sprite devrait posséder : Nom de l'entité, nom du type de l'entité, position (x, y), taille (x, y) (DONE)
- Définir le protocole de connexion d'un client : 
  -> Le client se connecte , envoie "connect"
  -> Le server répond "OK + numero de game + numero joueur"
  -> Le server envoie les packet "initialisation" (Types de monstres, types d'obstacles, etc...)
  -> Le client génère son init (en thread ?) renvoie "OK" quand il a fini
  -> Le server lui envoie les positions des sprites en cours
  -> Le server passe en UDP et reçoit les commandes du client classique (DONE)

**Comment by Rekkuzan** [comment]
J'oubliais aussi : 
(new) - Packet pour annoncer que la partie est finie. (le client se ferme) (DONE)

**Comment by Rekkuzan** [comment]
Encore un oublie (je l'avais mis en haut, mais pas en temps que truc à rajouté) : 
(new) - Packet pour envoyer numéro du joueur et Game (DONE)

**Comment by Rekkuzan** [comment]
(Le dernier rajout promis)
(modif) - Rajouter un id dans headerPacket (pour identifier les clients)
Tous les clients enverront donc leur id dans le packetHeader pour les reconnaitre (DONE)

**Comment by AntoineDewaele** [comment]
ScrollingPacket done

**Comment by AntoineDewaele** [comment]
Path dans positionPacket done

**Comment by AntoineDewaele** [comment]
rajout des erreurs done

**Comment by AntoineDewaele** [comment]
Tout est done.
