### ISSUE TITLE
Compilation Unix

### ISSUE THREAD

**Issue by beauraF** [RTYPE-EPITECH/RType#7]
RType/Server/Sources/MonsterFactory.o:(.rodata._ZTV15UDynamicLibraryIP8IMonsterE[_ZTV15UDynamicLibraryIP8IMonsterE]+0x20): référence indéfinie vers « UDynamicLibrary<IMonster*>::loadLibrary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) »
RType/Server/Sources/MonsterFactory.o:(.rodata._ZTV15UDynamicLibraryIP8IMonsterE[_ZTV15UDynamicLibraryIP8IMonsterE]+0x28): référence indéfinie vers « UDynamicLibrary<IMonster*>::useFunction() const »
RType/Server/Sources/MonsterFactory.o:(.rodata._ZTV15UDynamicLibraryIP8IMonsterE[_ZTV15UDynamicLibraryIP8IMonsterE]+0x30): référence indéfinie vers « UDynamicLibrary<IMonster*>::freeLibrary() »
collect2: error: ld returned 1 exit status

**Comment by Rekkuzan** [comment]
Je m'en charge.
